name: Elixir CI

on:
  push:
    branches: [ elixir ]
  pull_request:
    branches: [ elixir ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.12.3'
        otp-version: '24.1'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Check formatting
      run: mix format --check-formatted
