name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: ${{matrix.os}} - Build and test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2022]

    steps:
    - name: Configure Git
      run: -
        # Make line endings on Windows compatible with mix format
        git config --global core.autocrlf false
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: latest
        otp-version: '27'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Check formatting
      if: startsWith(matrix.os, 'ubuntu')
      run: mix format --check-formatted
